name: CI/CD Workflow

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package
    - uses: actions/upload-artifact@v4
      with:
        name: verademo.war
        path: target/verademo.war

  pipeline_scan:
    needs: build
    runs-on: ubuntu-latest
    name: Veracode Pipeline Scan
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: get archive
      uses: actions
